#!/usr/bin/env python3
"""
Regenerate tests/fixtures/standings_golden.json.

The golden file is the contract between standings.py and frontend/lib.js:
both are fed the same league over the same ESPN payload and both must produce the same
finishing order. Run this only when the RULE changes on purpose -- if it changes by
accident, the failing test is the point.

    python tools/make_golden.py
"""

import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
sys.path.insert(0, os.path.join(ROOT, "tests"))

import espn_leaderboard                                            # noqa: E402
import standings                                                   # noqa: E402
from test_standings import golden_case, GOLDEN                     # noqa: E402


def main():
    fixture = os.path.join(ROOT, "tests", "fixtures", "espn_final_with_cut.json")
    with open(fixture) as f:
        players = espn_leaderboard.parse_leaderboard(json.load(f))[1]

    case = golden_case(players)
    rows = standings.compute(case["teams"], case["by_name"])
    payload = {
        "note": ("Generated by tools/make_golden.py from the finished-tournament fixture. "
                 "The contract "
                 "between standings.py and frontend/lib.js -- if they disagree "
                 "about who is winning, tests/test_frontend_parity.py fails."),
        "source": "tests/fixtures/espn_final_with_cut.json",
        "teams": case["teams"],
        "expected": [{
            "team_id": r["team_id"],
            "position": r["position"],
            "rank": r["rank"],
            "decided_at": r["decided_at"],
            "counting": r["counting"],
            "vector": [list(v) for v in r["vector"]],
        } for r in rows],
    }

    os.makedirs(os.path.dirname(GOLDEN), exist_ok=True)
    with open(GOLDEN, "w") as f:
        json.dump(payload, f, indent=2)
        f.write("\n")
    print(f"wrote {GOLDEN}")
    for row in payload["expected"]:
        print(f"  {row['position']:>3}  {row['team_id']:<8} decided_at={row['decided_at']} "
              f"vector={row['vector']}")


if __name__ == "__main__":
    main()
